config/routes.rb
Rails.application.routes.draw do
  resources :travels do
    get 'export' , to: 'travels#export', as: :export
  end

  resources :tipos

  resources :costs

  resources :schedulings

  resources :travels do
    resources :costs
  end

  resources :homes

  devise_for :users

   root 'homes#index'

end

app/models/travel.rb
class Travel < ActiveRecord::Base
  belongs_to :user
  #has_many :schedulings, dependent: :destroy
  #has_many :users, through: :schedulings
  validates :destino, presence: true
  has_many :costs, dependent: :destroy

  #def self.to_csv(options = {})
  #CSV.generate(options) do |csv|
   # csv << column_names
    #all.each do |travel|
     # csv << travel.attributes.values_at(*column_names)
    #end
 # end
#end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: [:show, :edit, :update, :destroy]

  # GET /travels
  # GET /travels.json
  def index
    if current_user.present?
    @travels = current_user.travels
    respond_to do |format|
      format.html
      format.csv { render text: @travels.to_csv }
      format.xls #{ send_data @travels.to_csv(col_sep: "\t") }
    end
    else
      redirect_to '/users/sign_in'
    end
    
  end

  # GET /travels/1
  # GET /travels/1.json
  def show
    @total= @travel.costs.pluck(:valor).sum
  end

  # GET /travels/new
  def new
    if current_user.present?
    @travel = Travel.new
    else
      redirect_to '/users/sign_in'
    end
  end

  # GET /travels/1/edit
  def edit
  end

  # POST /travels
  # POST /travels.json
  def create
    @travel = Travel.new(travel_params)
    @travel.user = current_user

    respond_to do |format|
      if @travel.save
        format.html { redirect_to @travel, notice: 'Travel was successfully created.' }
        format.json { render :show, status: :created, location: @travel }
      else
        format.html { render :new }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travels/1
  # PATCH/PUT /travels/1.json
  def update
    respond_to do |format|
      if @travel.update(travel_params)
        format.html { redirect_to @travel, notice: 'Travel was successfully updated.' }
        format.json { render :show, status: :ok, location: @travel }
      else
        format.html { render :edit }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travels/1
  # DELETE /travels/1.json
  def destroy
    @travel.destroy
    respond_to do |format|
      format.html { redirect_to travels_url, notice: 'Travel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def export
      if current_user.present?
        @travel = Travel.find(params[:travel_id])
        @cost = @travel.costs
        @total= @travel.costs.pluck(:valor).sum
        respond_to do |format|
        format.html
        format.csv
        format.xls #{send_data @viagem.despesas.to_csv(col_sep: "\t") }
        end
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travel
      @travel = Travel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def travel_params
      params.require(:travel).permit(:destino, :data)
    end
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/travels/_form.html.erb
<%= form_for(@travel) do |f| %>
  <% if @travel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@travel.errors.count, "error") %> prohibited this travel from being saved:</h2>

      <ul>
      <% @travel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :destino %><br>
    <%= f.text_field :destino %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/travels/edit.html.erb
<div id="centralize">
<h1>Editing travel</h1>

<%= render 'form' %>

<%= link_to 'Show', @travel %> |
<%= link_to 'Back', travels_path %>
</div>

app/views/travels/export.csv.erb
<%
headers = [ "User", "Data", "Destino", "Total"]

  headers1 = ["Tipo","Valor Custo"]

  csv_output = CSV.generate do |csv|
    csv << headers

      csv << [
        current_user.name,
        @travel.data.strftime("%d-%m-%Y"),
        @travel.destino,
        @total
      ]
  end

  csv_output2 = CSV.generate do |csv|
    csv << headers1

      @travel.costs.each do |cost|
      csv << [
        
          cost.tipo.description,
          cost.valor
        ]
      
    end
  end


%>

<%= csv_output.html_safe %>
<%= csv_output2.html_safe %>

app/views/travels/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Usuario</Data></Cell>
        <Cell><Data ss:Type="String">Data</Data></Cell>
        <Cell><Data ss:Type="String">Destino</Data></Cell>
        <Cell><Data ss:Type="String">Total</Data></Cell>

      </Row>
      <Row>
        <Cell><Data ss:Type="String"><%= current_user.name %></Data></Cell>       
        <Cell><Data ss:Type="String"><%= @travel.data %></Data></Cell>
        <Cell><Data ss:Type="String"><%= @travel.destino %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= @total %></Data></Cell>
      </Row>
   
    </Table>
    <Table>
      <Row>
          <Cell><Data ss:Type="String">Cost</Data></Cell>
          <Cell><Data ss:Type="String">Valor do custo</Data></Cell>
      </Row>
      <% @travel.costs.each do |cost| %>
        <Row>
            <Cell><Data ss:Type="String"><%= cost.tipo.description %></Data></Cell>
            <Cell><Data ss:Type="Number"><%= cost.valor %></Data></Cell>
        </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/travels/index.html.erb
<div id="centralize">

<h1>Travels</h1>

<table>
  <thead>
    <tr>
      <th>Destination</th>
      <th>Date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @travels.each do |travel| %>
      <tr>
        <td><%= travel.destino %></td>
        <td><%= travel.data.strftime("%d-%m-%Y") %></td>
        <td><%= current_user.name %></td>
        <td><%= link_to 'Show', travel %></td>
        <td><%= link_to 'Edit', edit_travel_path(travel) %></td>
        <td><%= link_to 'Destroy', travel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<tr>
<td><%= link_to 'New Travel', new_travel_path %></td>
  </tr>
</div>  

app/views/travels/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Release Date</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.released_on %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.price %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/travels/new.html.erb
<div id="centralize">
<h1>New travel</h1>

<%= render 'form' %>

<%= link_to 'Back', travels_path %>
</div>

app/views/travels/show.html.erb
<div id="centralize">
<p id="notice"><%= notice %></p>

<strong><h2>Destino:</h2></strong>
  <%= @travel.destino %> (<%= @travel.data.strftime("%d-%m-%Y") %>)

  

  <strong><h3>Costs</h3></strong>
	<table>
  		<thead>
    		<tr>
      		<th>Value</th>
      		<th>Date</th>
      		<th>Type</th>
      		<th colspan="3"></th>
    		</tr>
  		</thead>

  		<tbody>

    		<% @travel.costs.each do |cost| %>
      	<tr>
        	<td><%= cost.valor %></td>
        	<td><%= cost.data.strftime("%d-%m-%Y") %></td>
        	<td><%= cost.tipo.description %></td>
        	<td><%= link_to 'Show', [@travel,cost] %></td>
       	 	<td><%= link_to 'Edit', edit_travel_cost_path(@travel,cost) %></td>
        	<td><%= link_to 'Destroy', [@travel,cost], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      	</tr>
    	<% end %>
  	</tbody>
	</table>

	<p>
    <strong>Value total:</strong> <%= @total %>
  </p>



<%= link_to 'Edit', edit_travel_path(@travel) %> |
<%= link_to 'Back', travels_path %>
<p>
  <strong>New Cost:</strong>
  </p>
<%= link_to 'New Cost', new_travel_cost_path(@travel) %>
<%= link_to 'Costs', travel_costs_path(@travel)%>

<strong><h2>Download:</h2></strong>
<%= link_to "Excel", travel_export_path(@travel, format: "xls") %>
<%= link_to "CSV", travel_export_path(@travel, format: "csv") %>



</div>