config/routes.rb
Rails.application.routes.draw do
  resources :travels do
    get 'export' , to: 'travels#export', as: :export
  end

  resources :tipos

  resources :costs

  resources :schedulings

  resources :travels do
    resources :costs
  end

  resources :homes

  devise_for :users

   root 'homes#index'

end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :travel
  belongs_to :tipo
  validates :valor, presence: true
  validates :valor, numericality: true
  validates :cover, :attachment_presence => true

  has_attached_file :cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
   		validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/



def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |cost|
      csv << cost.attributes.values_at(*column_names)
    end
  end
end


end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @travel = Travel.find(params[:travel_id])
    if current_user.present?
      @costs = @travel.costs
      respond_to do |format|
      format.html
      format.csv { render text: @costs.to_csv }
      format.xls #{ send_data @travels.to_csv(col_sep: "\t") }
    end
      else
      redirect_to '/users/sign_in'
    end
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
   
  end

  # GET /costs/new
  def new
    @travel = Travel.find(params[:travel_id])
    if current_user.present?
    @cost = @travel.costs.new
    else
      redirect_to '/users/sign_in'
    end
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @travel = Travel.find(params[:travel_id])
    @cost = @travel.costs.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to travel_cost_path(@travel,@cost), notice: 'Custo was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to homes_path, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:tipo, :valor, :data, :travel_id, :tipo_id, :cover)
    end

    
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for [@travel,@cost] do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <style type="text/css">

  #content2{
        display: none;
      }
  </style>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.collection_select(:tipo_id, Tipo.order(:description), :id, :description)%>
  </div>
  
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor%>
  </div>
  
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div id = "content2">
    <%= f.label :travel_id %><br>
    <%= f.text_field :travel_id %>
  </div>
  <div class="field">
    <%= f.label :cover %><br>
    <%= f.file_field :cover %>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
  <div><h2><Strong>New tipo</h2></Strong>
  <%= link_to 'New Tipo', new_tipo_path %>
</div>
<% end %>

app/views/costs/edit.html.erb
<div id="centralize">
<h1>Editing cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', travels_path %>
</div>

app/views/costs/index.html.erb
<div id="centralize">
<h1>Listing costs</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Value</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.tipo.description %></td>
        <td><%= cost.valor %></td>
        <td><%= cost.data.strftime("%d-%m-%Y") %></td>
        <td><%= link_to 'Show', [@travel,cost] %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cost', new_travel_cost_path %>
<%= link_to 'Return to Travel', travels_path %>

<strong><h2>Download:</h2></strong>
<%= link_to "CSV", travel_costs_path(format: "csv") %>
<%= link_to "Excel", travel_costs_path(format: "xls") %>


</div>

app/views/costs/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">User</Data></Cell>
        <Cell><Data ss:Type="String">Data</Data></Cell>
        <Cell><Data ss:Type="String">Destino</Data></Cell>
        <Cell><Data ss:Type="String">Descrição</Data></Cell>
        <Cell><Data ss:Type="String">Valor</Data></Cell>
        <Cell><Data ss:Type="String">Total</Data></Cell>
      </Row>

    <% @costs.each do |cost| %>
      <Row>
        <Cell><Data ss:Type="String"><%= current_user.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= cost.travel.data %></Data></Cell>
        <Cell><Data ss:Type="String"><%= cost.travel.destino %></Data></Cell>
        <Cell><Data ss:Type="String"><%= cost.tipo.description %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= cost.valor %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= total= @travel.costs.pluck(:valor).sum  %></Data></Cell>

         

       
         
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/costs/new.html.erb
<div id="centralize">
<h1>New cost</h1>

<%= render 'form' %>

<%= link_to 'Back', travel_costs_path %>
</div>

app/views/costs/show.html.erb
<div id="centralize">
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @cost.tipo.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @cost.valor %>
</p>

<p>
  <strong>Date:</strong>
  <%= @cost.data.strftime("%d-%m-%Y") %>
</p>

<p>
	<p><strong>Nota Fiscal</strong></p>
	<%= image_tag @cost.cover.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', travels_path %>



</div>