config/routes.rb
Rails.application.routes.draw do
  resources :travels do
    get 'export' , to: 'travels#export', as: :export
  end

  resources :tipos

  resources :costs

  resources :schedulings

  resources :travels do
    resources :costs
  end

  resources :homes

  devise_for :users

   root 'homes#index'

end

app/models/scheduling.rb
class Scheduling < ActiveRecord::Base
  belongs_to :user
  belongs_to :travel
end

app/controllers/schedulings_controller.rb
class SchedulingsController < ApplicationController
  before_action :set_scheduling, only: [:show, :edit, :update, :destroy]

  # GET /schedulings
  # GET /schedulings.json
  def index
    @schedulings = Scheduling.all
  end

  # GET /schedulings/1
  # GET /schedulings/1.json
  def show
  end

  # GET /schedulings/new
  def new
    @scheduling = Scheduling.new
  end

  # GET /schedulings/1/edit
  def edit
  end

  # POST /schedulings
  # POST /schedulings.json
  def create
    @scheduling = Scheduling.new(scheduling_params)

    respond_to do |format|
      if @scheduling.save
        format.html { redirect_to @scheduling, notice: 'Scheduling was successfully created.' }
        format.json { render :show, status: :created, location: @scheduling }
      else
        format.html { render :new }
        format.json { render json: @scheduling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedulings/1
  # PATCH/PUT /schedulings/1.json
  def update
    respond_to do |format|
      if @scheduling.update(scheduling_params)
        format.html { redirect_to @scheduling, notice: 'Scheduling was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduling }
      else
        format.html { render :edit }
        format.json { render json: @scheduling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedulings/1
  # DELETE /schedulings/1.json
  def destroy
    @scheduling.destroy
    respond_to do |format|
      format.html { redirect_to schedulings_url, notice: 'Scheduling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduling
      @scheduling = Scheduling.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheduling_params
      params.require(:scheduling).permit(:user_id, :travel_id)
    end
end

app/helpers/schedulings_helper.rb
module SchedulingsHelper
end

app/views/schedulings/_form.html.erb
<%= form_for(@scheduling) do |f| %>
  <% if @scheduling.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scheduling.errors.count, "error") %> prohibited this scheduling from being saved:</h2>

      <ul>
      <% @scheduling.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select(:user_id, User.order(:name), :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :travel_id %><br>
    <%= f.collection_select(:travel_id, Travel.order(:destino), :id, :destino) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedulings/edit.html.erb
<h1>Editing scheduling</h1>

<%= render 'form' %>

<%= link_to 'Show', @scheduling %> |
<%= link_to 'Back', schedulings_path %>

app/views/schedulings/index.html.erb
<h1>Listing schedulings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Travel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedulings.each do |scheduling| %>
      <tr>
        <td><%= scheduling.user.name %></td>
        <td><%= scheduling.travel.destino %></td>
        <td><%= link_to 'Show', scheduling %></td>
        <td><%= link_to 'Edit', edit_scheduling_path(scheduling) %></td>
        <td><%= link_to 'Destroy', scheduling, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scheduling', new_scheduling_path %>
<%= link_to 'Return to Travel', travels_path %>

app/views/schedulings/new.html.erb
<h1>New scheduling</h1>

<%= render 'form' %>

<%= link_to 'Back', schedulings_path %>

app/views/schedulings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @scheduling.user.name %>
</p>

<p>
  <strong>Travel:</strong>
  <%= @scheduling.travel.destino %>
</p>

<%= link_to 'Edit', edit_scheduling_path(@scheduling) %> |
<%= link_to 'Back', schedulings_path %>